#-------------------------------
# General Site Settings
title: Alisong
logo: '/images/logo.png' # You can add own logo. For example '/images/logo.png'.
description: This is the book of my coding journey.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://alisongh.com" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Alison Huang
  avatar: '/images/image.jpg'


#-------------------------------
# Hero Settings
hero:
  title: Alison Huang
  description: To Blog = To Share, To Connect, To Create, To Inspire
  image: '/images/01.jpg'


#-------------------------------
# Contact Settings
contact:
  email: liwenh@umich.edu # Add your email for contact form
  description: Please subscribe the newsletter first.
  
# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/alisonliwenhuang/"}
- {icon: "ion-logo-github", link: "https://github.com/alisongh"}



#-------------------------------
# Comment Section (Disqus)
disqus-identifier: alisongh # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-ZKBV0G1GKQ # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: "github.us5.list-manage.com/subscribe/post?u=d44e91f32e81e0bbf09e37cdb&amp;id=fa8ba8225c" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
